apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-es-log-volume
  namespace: uat
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-volume"
    path: "glusterfs-volume"
    readOnly: false
