apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: uat
  name: emqx
  labels:
    app: emqx
spec:
  serviceName: emqx-headless
  updateStrategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - emqx
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "app"
                  operator: In
                  values: ["middleware"]
      serviceAccountName: emqx
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: emqx
        image: 10.150.30.17:28080/ops/emqx:4.3.8
        ports:
        - name: mqtt
          containerPort: 1883
        - name: mqttssl
          containerPort: 8883
        - name: mgmt
          containerPort: 8081
        - name: ws
          containerPort: 8083
        - name: wss
          containerPort: 8084
        - name: dashboard
          containerPort: 18083
        - name: ekka
          containerPort: 4370
        env:
          - name: EMQX_CLUSTER__DISCOVERY
            value: k8s
          - name: EMQX_NAME
            value: emqx
          - name: EMQX_CLUSTER__K8S__APISERVER
            value: https://kubernetes.default.svc.retailcluster.local:443
          - name: EMQX_CLUSTER__K8S__NAMESPACE
            value: uat
          - name: EMQX_CLUSTER__K8S__SERVICE_NAME
            value: emqx-headless
          - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
            value: hostname
          - name: EMQX_CLUSTER__K8S__APP_NAME
            value: emqx
          - name: EMQX_CLUSTER__K8S__SUFFIX
            value: svc.retailcluster.local
---
apiVersion: v1
kind: Service
metadata:
  namespace: uat
  name: emqx-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: emqx
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  - name: mqttssl
    port: 8883
    protocol: TCP
    targetPort: 8883
  - name: mgmt
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: websocket
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: wss
    port: 8084
    protocol: TCP
    targetPort: 8084
  - name: dashboard
    port: 18083
    protocol: TCP
    targetPort: 18083
  - name: ekka
    port: 4370
    protocol: TCP
    targetPort: ekka
