apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  labels:
    app: emqx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "emqx"
                  operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - emqx
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
      - name: harbor-secret
      hostNetwork: true
      containers:
      - name: emqx
        image: swr.cn-east-2.myhuaweicloud.com/shsl-ops/emqx:4.4.3
        imagePullPolicy: IfNotPresent
        ports:
        - name: mqtt
          containerPort: 1883
        - name: mqttssl
          containerPort: 8883
        - name: mgmt
          containerPort: 8081
        - name: ws
          containerPort: 8083
        - name: wss
          containerPort: 8084
        - name: dashboard
          containerPort: 18083
        - name: ekka
          containerPort: 4370
        env:
          - name: EMQX_LOADED_PLUGINS # 加载用户名密码插件
            value: emqx_auth_mnesia
          - name: EMQX_ALLOW_ANONYMOUS # 禁止匿名访问
            value: "false"
          - name: EMQX_NAME
            value: emqx
          - name: EMQX_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: EMQX_CLUSTER__DISCOVERY
            value: static
          - name: EMQX_CLUSTER__STATIC__SEEDS
            value: "emqx@172.16.3.31,emqx@172.16.3.32"
        resources:
          requests:
            memory: 500Mi
            cpu: 0.1
          limits:
            memory: 1Gi
            cpu: 1
        volumeMounts:
          - name: emqx-auth-mnesia-conf
            mountPath: /opt/emqx/etc/plugins/emqx_auth_mnesia.conf
            subPath: emqx_auth_mnesia.conf
          - name: emqx-data
            mountPath: /opt/emqx/data
          - name: emqx-log
            mountPath: /opt/emqx/log
      initContainers:
        - name: fix-permissions 
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["sh", "-c", "chmod -R 777 /opt/emqx/data /opt/emqx/log"]          
          volumeMounts:
            - name: emqx-data
              mountPath: /opt/emqx/data
            - name: emqx-log
              mountPath: /opt/emqx/log
      volumes:
      - name: emqx-auth-mnesia-conf
        configMap:
          name: emqx-conf
          items:
          - key: emqx_auth_mnesia.conf
            path: emqx_auth_mnesia.conf
      - name: emqx-data
        hostPath:
          path: /data/emqx/data
      - name: emqx-log
        hostPath:
          path: /data/emqx/log
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: emqx
spec:
  selector:
    app: emqx
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  - name: mqttssl
    port: 8883
    protocol: TCP
    targetPort: 8883
  - name: mgmt
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: websocket
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: wss
    port: 8084
    protocol: TCP
    targetPort: 8084
  - name: dashboard
    port: 18083
    protocol: TCP
    targetPort: 18083
  - name: ekka
    port: 4370
    protocol: TCP
    targetPort: ekka