apiVersion: apps/v1
kind: Deployment
metadata:
  name: zkui
spec:
  selector:
    matchLabels:
      app: zkui
  replicas: 1
  template:
    metadata:
      labels:
        app: zkui
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - rocketmq-master-a
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "app"
                  operator: In
                  values: ["middleware"]
      imagePullSecrets:
        - name: harbor-secret
      containers:
      - name: zkui 
        imagePullPolicy: Always
        image: 10.150.30.17:28080/ops/zkui:latest
        env:
        - name: ZKLIST
          value: "zk-0.zookeeper.uat.svc.retailcluster.local:2181,zk-1.zookeeper.uat.svc.retailcluster.local:2181,zk-2.zookeeper.uat.svc.retailcluster.local:2181"
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "500Mi"
        ports:
          - containerPort: 9090
            name: client
        readinessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 5
      
---
apiVersion: v1
kind: Service
metadata:
  name: zkui
  labels:
    app: zkui
spec:
  selector:
    app: zkui
  clusterIP: None
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: zkui
