apiVersion: v1
data:
  zoo.cfg: |
    tickTime=2000
    initLimit=10
    syncLimit=5
    dataDir=/opt/zookeeper/zookeeper_data
    dataLogDir=/data/zookeeper/zookeeper_log
    clientPort=2181
    maxClientCnxns=0
    server.0=zk-0.zookeeper.uat.svc.retailcluster.local:2888:3888
    server.1=zk-1.zookeeper.uat.svc.retailcluster.local:2888:3888
    server.2=zk-2.zookeeper.uat.svc.retailcluster.local:2888:3888
    autopurge.snapRetainCount=50
    autopurge.purgeInterval=24
  setmyid: |
    #!/bin/sh
    HOST=`echo $PODNAME`
    IDFILE=$1
    #if [[ $HOST =~ (.*)-([0-9]+)$ ]]; then
    #  NAME=${BASH_REMATCH[1]}
    #  ORD=${BASH_REMATCH[2]}
    #else
    #  echo "Fialed to parse name and ordinal of Pod"
    #  exit 1
    #fi
    ORD=`echo $HOST|awk -F "-" '{print $2}'`
    MY_ID=$ORD
    if [[ ! -f $IDFILE ]]; then
      echo $MY_ID >> $IDFILE
    fi

kind: ConfigMap
metadata:
  name: zookeeper-conf
  namespace: uat

