apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: uat
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - middleware
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - kibana
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - image: 10.150.30.17:28080/ops/kibana:6.8.13
        imagePullPolicy: Always
        name: kibana
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://elasticsearch-log.uat.svc.retailcluster.local:9200
        ports:
        - containerPort: 5601

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: uat
spec:
  clusterIP: None
  ports:
  - name: kibana
    port: 5601
    targetPort: 5601
  selector:
    app: kibana
