apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketmq-conf
  namespace: uat
data:
  broker-a.conf: |
    listenPort=10911
    brokerClusterName=DefaultCluster
    brokerName=broker-a
    brokerId=0
    deleteWhen=04
    fileReservedTime=48
    brokerRole=ASYNC_MASTER
    flushDiskType=ASYNC_FLUSH
    defaultTopicQueueNums=4
    namesrvAddr=rocketmq-ns-0.rocketmq-ns.uat.svc.retailcluster.local:9876;rocketmq-ns-1.rocketmq-ns.uat.svc.retailcluster.local:9876
    #存储路径
    storePathRootDir=/data/rocketmq-a/store
    storePathCommitLog=/data/rocketmq-a/store/commitlog
    #消费队列存储路径存储路径
    storePathConsumeQueue=/data/rocketmq-a/store/consumequeue
    #消息索引存储路径
    storePathIndex=/data/rocketmq-a/store/index
    #checkpoint 文件存储路径
    storeCheckpoint=/data/rocketmq-a/store/checkpoint
    #abort 文件存储路径
    abortFile=/data/rocketmq-a/store/abort

  broker-as.conf: |
    listenPort=11911
    brokerClusterName=DefaultCluster
    brokerName=broker-a
    brokerId=1
    brokerRole=SLAVE
    deleteWhen=04
    fileReservedTime=48
    flushDiskType=ASYNC_FLUSH
    defaultTopicQueueNums=4
    namesrvAddr=rocketmq-ns-0.rocketmq-ns.uat.svc.retailcluster.local:9876;rocketmq-ns-1.rocketmq-ns.uat.svc.retailcluster.local:9876
    storePathRootDir=/data/rocketmq-a/store
    #commitLog 存储路径
    storePathCommitLog=/data/rocketmq-a/store/commitlog
    #消费队列存储路径存储路径
    storePathConsumeQueue=/data/rocketmq-a/store/consumequeue
    #消息索引存储路径
    storePathIndex=/data/rocketmq-a/store/index
    #checkpoint 文件存储路径
    storeCheckpoint=/data/rocketmq-a/store/checkpoint
    #abort 文件存储路径
    abortFile=/data/rocketmq-a/store/abort
  broker-b.conf: |
    listenPort=10911
    brokerClusterName=DefaultCluster
    brokerName=broker-b
    brokerId=0
    deleteWhen=04
    fileReservedTime=48
    brokerRole=ASYNC_MASTER
    flushDiskType=ASYNC_FLUSH
    defaultTopicQueueNums=4
    namesrvAddr=rocketmq-ns-0.rocketmq-ns.uat.svc.retailcluster.local:9876;rocketmq-ns-1.rocketmq-ns.uat.svc.retailcluster.local:9876
    storePathRootDir=/data/rocketmq-b/store
    #commitLog 存储路径
    storePathCommitLog=/data/rocketmq-b/store/commitlog
    #消费队列存储路径存储路径
    storePathConsumeQueue=/data/rocketmq-b/store/consumequeue
    #消息索引存储路径
    storePathIndex=/data/rocketmq-b/store/index
    #checkpoint 文件存储路径
    storeCheckpoint=/data/rocketmq-b/store/checkpoint
    #abort 文件存储路径
    abortFile=/data/rocketmq-b/store/abor

  broker-bs.conf: | 
    listenPort=11911
    brokerClusterName=DefaultCluster
    brokerName=broker-b
    brokerId=1
    brokerRole=SLAVE
    deleteWhen=04
    fileReservedTime=48
    flushDiskType=ASYNC_FLUSH
    defaultTopicQueueNums=4
    namesrvAddr=rocketmq-ns-0.rocketmq-ns.uat.svc.retailcluster.local:9876;rocketmq-ns-1.rocketmq-ns.uat.svc.retailcluster.local:9876
    storePathRootDir=/data/rocketmq-b/store
    #commitLog 存储路径
    storePathCommitLog=/data/rocketmq-b/store/commitlog
    #消费队列存储路径存储路径
    storePathConsumeQueue=/data/rocketmq-b/store/consumequeue
    #消息索引存储路径
    storePathIndex=/data/rocketmq-b/store/index
    #checkpoint 文件存储路径
    storeCheckpoint=/data/rocketmq-b/store/checkpoint
    #abort 文件存储路径
    abortFile=/data/rocketmq-b/store/abort

