apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-broker-a
  namespace: prod
  labels:
    app: rocketmq-broker-a

spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-broker-a
  template:
    metadata:
      labels:
        app: rocketmq-broker-a
    spec:
      nodeName: 172.16.3.12
      imagePullSecrets:
      - name: harbor-secret
      containers:
        - name: rocketmq-broker-a
          image: 10.150.30.17:28080/ops/rocketmq:4.8.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2
              memory: 3Gi
            requests:
              cpu: 0.5
              memory: 2Gi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPT_EXT
              value: -Xms2g -Xmx2g -Xmn1g
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          command: [ "sh","-c","mqbroker -c /etc/rocketmq/broker-a.conf" ]
          readinessProbe:
            tcpSocket:
              port: 10911
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 10911
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 10911
          volumeMounts:
            - name: rocketmq-broker-a-data
              mountPath: /home/rocketmq/store
            - name: rocketmq-broker-a-logs
              mountPath: /home/rocketmq/logs
            - name: rocketmq-broker-a-conf
              mountPath: /etc/rocketmq/broker-a.conf
              subPath: broker-a.conf
      initContainers:
        - name: fix-permissions 
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["sh", "-c", "chmod -R 777 /home/rocketmq/store /home/rocketmq/logs"]          
          volumeMounts:
            - name: rocketmq-broker-a-data
              mountPath: /home/rocketmq/store
            - name: rocketmq-broker-a-logs
              mountPath: /home/rocketmq/logs
      volumes:
        - name: rocketmq-broker-a-data
          hostPath: 
            path: /data/rocketmq-broker-a/data
        - name: rocketmq-broker-a-logs
          hostPath:
            path: /data/rocketmq-broker-a/logs
        - name: rocketmq-broker-a-conf
          configMap:
            name: rocketmq-conf
            items: 
            - key: broker-a.conf
              path: broker-a.conf