apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketmq-conf
  namespace: prod
data:
  broker-a.conf: |
    listenPort=10911
    brokerClusterName=DefaultCluster
    brokerName=broker-a
    brokerId=0
    deleteWhen=04
    fileReservedTime=48
    brokerRole=ASYNC_MASTER
    flushDiskType=ASYNC_FLUSH
    defaultTopicQueueNums=4
    namesrvAddr=rocketmq-ns-0.rocketmq-ns.prod.svc.cluster.local:9876;rocketmq-ns-1.rocketmq-ns.prod.svc.cluster.local:9876

  broker-as.conf: |
    listenPort=11911
    brokerClusterName=DefaultCluster
    brokerName=broker-a
    brokerId=1
    brokerRole=SLAVE
    deleteWhen=04
    fileReservedTime=48
    flushDiskType=ASYNC_FLUSH
    defaultTopicQueueNums=4
    namesrvAddr=rocketmq-ns-0.rocketmq-ns.prod.svc.cluster.local:9876;rocketmq-ns-1.rocketmq-ns.prod.svc.cluster.local:9876
  broker-b.conf: |
    listenPort=10911
    brokerClusterName=DefaultCluster
    brokerName=broker-b
    brokerId=0
    deleteWhen=04
    fileReservedTime=48
    brokerRole=ASYNC_MASTER
    flushDiskType=ASYNC_FLUSH
    defaultTopicQueueNums=4
    namesrvAddr=rocketmq-ns-0.rocketmq-ns.prod.svc.cluster.local:9876;rocketmq-ns-1.rocketmq-ns.prod.svc.cluster.local:9876

  broker-bs.conf: | 
    listenPort=11911
    brokerClusterName=DefaultCluster
    brokerName=broker-b
    brokerId=1
    brokerRole=SLAVE
    deleteWhen=04
    fileReservedTime=48
    flushDiskType=ASYNC_FLUSH
    defaultTopicQueueNums=4
    namesrvAddr=rocketmq-ns-0.rocketmq-ns.prod.svc.cluster.local:9876;rocketmq-ns-1.rocketmq-ns.prod.svc.cluster.local:9876