apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketmq-slave-b
  namespace: uat
  labels:
    app: rocketmq-slave-b

spec:
  serviceName: rocketmq-slave-b
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-slave-b
  template:
    metadata:
      labels:
        app: rocketmq-slave-b
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - rocketmq-slave-b
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "app"
                  operator: In
                  values: ["middleware"]
      imagePullSecrets:
      - name: harbor-secret
      containers:
        - name: rmqbroker-slave
          image: 10.150.30.17:28080/ops/rocketmq:4.8.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 450m
              memory: 3000Mi
            requests:
              cpu: 400m
              memory: 2000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPT_EXT
              value: -Xms1024M -Xmx1024M -Xmn256m
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          command: [ "sh","-c","mqbroker -c /etc/rocketmq/broker-bs.conf" ]
          readinessProbe:
            tcpSocket:
              port: 11911
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 11911
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 11911
            - containerPort: 11912
            - containerPort: 11913
          volumeMounts:
            - name: rocketmq-bs-data
              mountPath: /data/rocketmq-b/store
              subPathExpr: $(PODNAME)/rocketmq-bs-data
            - name: rocketmq-bs-logs
              mountPath: /home/rocketmq/logs
              subPathExpr: $(PODNAME)/rocketmq-bs-logs             
            - name: rocketmq-bs-conf
              mountPath: /etc/rocketmq/broker-bs.conf
              subPath: broker-bs.conf
      volumes:
        - name: rocketmq-bs-data
          persistentVolumeClaim:
            claimName: glusterfs-rocketmq-bs-data
        - name: rocketmq-bs-logs
          persistentVolumeClaim:
            claimName: glusterfs-rocketmq-bs-logs        
        - name: rocketmq-bs-conf
          configMap:
            name: rocketmq-conf
            items: 
            - key: broker-bs.conf
              path: broker-bs.conf
              


