apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-broker-as
  namespace: prod
  labels:
    app: rocketmq-broker-as

spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-broker-as
  template:
    metadata:
      labels:
        app: rocketmq-broker-as
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - rocketmq-broker-as
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - 172.16.3.12
      imagePullSecrets:
      - name: harbor-secret
      containers:
        - name: rocketmq-broker-as
          image: 10.150.30.17:28080/ops/rocketmq:4.8.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2
              memory: 3Gi
            requests:
              cpu: 0.5
              memory: 2Gi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPT_EXT
              value: -Xms2g -Xmx2g -Xmn1g
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: [ "sh","-c","mqbroker -c /etc/rocketmq/broker-as.conf" ]
          readinessProbe:
            tcpSocket:
              port: 11911
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 11911
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 11911
          volumeMounts:
            - name: rocketmq-broker-as-data
              mountPath: /home/rocketmq/store
            - name: rocketmq-broker-as-logs
              mountPath: /home/rocketmq/logs
            - name: rocketmq-broker-as-conf
              mountPath: /etc/rocketmq/broker-as.conf
              subPath: broker-as.conf
      initContainers:
        - name: fix-permissions 
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["sh", "-c", "chmod -R 777 /home/rocketmq/store /home/rocketmq/logs"]          
          volumeMounts:
            - name: rocketmq-broker-as-data
              mountPath: /home/rocketmq/store
            - name: rocketmq-broker-as-logs
              mountPath: /home/rocketmq/logs
      volumes:
        - name: rocketmq-broker-as-data
          hostPath:
            path: /data/rocketmq-broker-as/data
        - name: rocketmq-broker-as-logs
          hostPath:
            path: /data/rocketmq-broker-as/logs
        - name: rocketmq-broker-as-conf
          configMap:
            name: rocketmq-conf
            items: 
            - key: broker-as.conf
              path: broker-as.conf