kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-app-pv1
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/es-app
  persistentVolumeReclaimPolicy: Recycle
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 172.16.3.21
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-app-pv2
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/es-app
  persistentVolumeReclaimPolicy: Recycle
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 172.16.3.22
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-app-pv3
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/es-app
  persistentVolumeReclaimPolicy: Recycle
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 172.16.3.23