apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-app
  namespace: prod
spec:
  serviceName: es-app
  replicas: 3
  selector:
    matchLabels:
      app: es-app
  template:
    metadata:
      labels:
        app: es-app
    spec:
      imagePullSecrets:
      - name: harbor-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: es-app
                operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - es-app 
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: es-app 
          image: 10.150.30.17:28080/ops/elasticsearch:6.8.23
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
          - containerPort: 9200
            name: http
          - containerPort: 9300
            name: transport             
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: cluster.name
              value: "es-app"
            - name: discovery.zen.ping.unicast.hosts
              value: "es-app-0.es-app,es-app-1.es-app,es-app-2.es-app"
            - name: ES_JAVA_OPTS
              value: "-Xms4g -Xmx4g"
          resources:
            requests:
              memory: 4Gi
              cpu: 1
            limits:
              memory: 6Gi
          livenessProbe:
            tcpSocket:
              port: transport
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: http 
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 20
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
      initContainers:
        - name: fix-permissions 
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["sh", "-c", "chmod 777 /usr/share/elasticsearch/data"]          
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data

  volumeClaimTemplates:
  - metadata:
      name: es-data
      labels: 
        app: es-app
    spec:
      storageClassName: local-storage
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 250Gi
---
apiVersion: v1
kind: Service
metadata:
  name: es-app
  namespace: prod
  labels:
    app: es-app
spec:
  selector:
    app: es-app
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: http-port
    - protocol: TCP
      port: 9300
      targetPort: 9300
      name: trans-port