apiVersion: apps/v1
kind: Deployment
metadata:
  name: canal-admin
  labels:
    app: canal-admin
spec:
  selector:
    matchLabels:
      app: canal-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: canal-admin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: middleware
                operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - canal-admin
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: canal-admin
        image: 10.150.30.17:28080/ops/canal-admin:latest
        imagePullPolicy: Always
        resources:
          requets:
            memory: 1Gi
            cpu:  0.1
          limits:
            memory: 1500Mi
            cpu: 0.5
        env:
        - name: MYSQL_ADDR
          value: mysql.uat.svc.retailcluster.local:3306
        - name: MYSQL_DBNAME
          value: canal-admin
        - name: MYSQL_USER
          value: canal
        - name: MYSQL_PASSWD
          value: zGspYZQ6OS8o


---
apiVersion: v1
kind: Service
metadata:
  name: canal-admin
spec:
  ports:
  - name: canal-admin
    port: 8089
    targetPort: 8089
  selector:
    app: canal-admin

