apiVersion: apps/v1
kind: Deployment
metadata:
  name: canal-server
  namespace: dev
  labels:
    app: canal-server
spec:
  selector:
    matchLabels:
      app: canal-server
  replicas: 1
  template:
    metadata:
      labels:
        app: canal-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - middleware
              - key: env
                operator: In
                values:
                - dev
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - canal-server
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: canal-server
        image: 10.150.30.17:28080/ops/canal-server:v1.1.5
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi" 
          requests:
            memory: "1Gi"  
        env:
        - name: CANAL_ADMIN_ADDR
          value: canal-admin.dev.svc.retailcluster.local:8089
        - name: REGISTER_IP
          value: canal-server.dev.svc.retailcluster.local



---
apiVersion: v1
kind: Service
metadata:
  name: canal-server
  namespace: dev
spec:
  clusterIP: None
  ports:
  - name: admin
    port: 11110
    targetPort: 11110
  - name: tcp
    port: 11111
    targetPort: 11111
  - name: metric
    port: 11112
    targetPort: 11112
  selector:
    app: canal-server

