apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec: 
      hostNetwork: true
      serviceAccount: traefik-ingress-controller
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: jixson/traefik:v1.7
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 300m
            memory: 200Mi
          requests:
            cpu: 20m
            memory: 30Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        - name: admin
          containerPort: 8080
          protocol: TCP
        args:
        - --configfile=/config/traefik.toml
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --web
        - --accesslog
        - --accessLog.filePath=/var/log/traefik/access.log
        volumeMounts:
        - mountPath: /ssl
          name: ssl
        - mountPath: /config
          name: config
        - name: timezone
          mountPath: /etc/localtime
      dnsPolicy: ClusterFirstWithHostNet 
      restartPolicy: Always
      tolerations:
        - key: "ingress"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ingress
                operator: In
                values:
                - "true"
      volumes:
      - name: ssl
        secret:
          defaultMode: 0644
          secretName: traefik-ssl
      - configMap:
          defaultMode: 0420
          name: traefik-conf
        name: config
      - name: timezone
        hostPath:
          path: /etc/localtime
---
