apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: uat
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeName: local-retail-worker-2 
      imagePullSecrets:
      - name: harbor-secret    
      containers:
      - name: grafana
        image: 10.150.30.17:28080/ops/grafana:7.5.7
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
            name: http-grafana
            protocol: TCP
        readinessProbe: #pod就绪探针
          failureThreshold: 3
          httpGet:
            path: /robots.txt
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe: #pod存活探针
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 1            
        resources:
          requests:
            memory: 500Mi
          limits:
            memory: 1Gi
        volumeMounts:
          - name: grafana-data
            mountPath: /var/lib/grafana
      volumes:
        - name: grafana-data
          hostPath:
            path: /data/uat/grafana/data
---
apiVersion: v1
kind: Service
metadata:
  namespace: uat
  name: grafana
spec:
  clusterIP: None
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None