apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn
  namespace: dev
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openvpn
  replicas: 1
  template:
    metadata:
      labels:
        app: openvpn
    spec:
      nodeName: 192.168.1.11
      containers:
      - image: hyr326/openvpn-manager:sqlite
        imagePullPolicy: Always
        name: openvpn
        securityContext:
          capabilities:
            add: 
            - NET_ADMIN
            drop:
            - KILL
        resources:
          requests:
            memory: "500Mi"
        ports:
        - name: web
          containerPort: 80
        - name: openvpn
          containerPort: 1194
        env:
          - name: OVPN_ADDR
            value: 0.0.0.0
          - name: OVPN_PROTO
            value: tcp
        volumeMounts:
        - name: openvpn-conf
          mountPath: /etc/openvpn/
        - name: openvpn-data
          mountPath: /data
      volumes:
      - name: openvpn-data
        hostPath:
          path: /data/openvpn/data
      - name: openvpn-conf
        hostPath:
          path: /data/openvpn/conf


---
apiVersion: v1
kind: Service
metadata:
  name: openvpn
  namespace: dev
spec:
  type: NodePort
  ports:
  - name: web
    port: 80
    targetPort: 80
    nodePort: 31080
  - name: openvpn
    port: 1194
    targetPort: 1194
    nodePort: 31094
  selector:
    app: openvpn