apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: uat
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeName: local-retail-worker-2
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - image: 10.150.30.17:28080/ops/mongo:4.2
        imagePullPolicy: Always
        name: mongo
        args:
        - mongod 
        - "--bind_ip" 
        - "0.0.0.0"
        - "--replSet"
        - "retailrs"
        - "--auth"
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: admin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: dFrYbr6ksV
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        hostPath:
          path: /data/uat/mongo/data


---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: uat
spec:
  type: NodePort
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
    nodePort: 30717
  selector:
    app: mongo
