apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-es-app-volume
  namespace: uat
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-volume"
    path: "glusterfs-volume"
    readOnly: false
