apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-app
  namespace: uat
spec:
  serviceName: elasticsearch-app
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch-app
  template:
    metadata:
      labels:
        app: elasticsearch-app
    spec:
      imagePullSecrets:
      - name: harbor-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - "middleware"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - elasticsearch-app 
              topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
      containers:
        - name: elasticsearch 
          image: 10.150.30.17:28080/ops/elasticsearch:6.8.13
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
          - containerPort: 9200
            name: outer
          - containerPort: 9300
            name: inner             
          env:
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - sh
            - -c
            - "/usr/share/elasticsearch/bin/elasticsearch"
          resources:
            requests:
              memory: 1024Mi
              cpu: 500m
            limits:
              memory: 2500Mi
              cpu: 1000m
          livenessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 9200 
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 20
          volumeMounts:
            - name: elasticsearch-yml 
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            - name: jvm-options 
              mountPath: /usr/share/elasticsearch/config/jvm.options
              subPath: jvm.options
            - name: elasticsearch-data
              mountPath: /opt/elasticsearch/
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: elasticsearch-yml
          configMap:
            name: elasticsearch-conf
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
        - name: jvm-options 
          configMap:
            name: elasticsearch-conf
            items:
              - key: jvm.options 
                path: jvm.options
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: glusterfs-elasticsearch-app
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-app
  namespace: uat
  labels:
    app: elasticsearch-app
spec:
  clusterIP: None
  selector:
    app: elasticsearch-app
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: http-port
    - protocol: TCP
      port: 9300
      targetPort: 9300
      name: trans-port

