---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cm
  namespace: uat
data:
  redis.conf: |
    port 6379
    bind 0.0.0.0
    loglevel notice
    timeout 0
    tcp-keepalive 60
    activerehashing no
    #save 900 1
    #save 300 10
    #save 60 10000
    #dbfilename dump-6379.rdb
    dir /data
    maxmemory 4gb
    maxmemory-policy volatile-lru
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    notify-keyspace-events Kx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: uat
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - redis
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - redis 
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: redis
        image: 10.150.30.17:28080/ops/redis:5
        imagePullPolicy: Always
        resources:
          requests:
            memory: 2Gi
            cpu: 0.5
          limits:
            memory: 4Gi
            cpu: 1
        args:
        - "redis-server"
        - "/usr/local/etc/redis/redis.conf" 
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data/
        - name: redis-conf
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
      volumes:
      - name: redis-data
        hostPath:
          path: /data/uat/redis/data
      - name: redis-conf
        configMap:
          name: redis-cm


---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: uat
spec:
  type: NodePort
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    nodePort: 30379
  selector:
    app: redis
